#!/bin/bash

self=.

unset ok2create
while test -n "$1"; do
    opt=$1 && shift
    if test $opt == --ok2create; then
        ok2create=1
    else
        echo unknown argument: $opt >&2
        exit 1
    fi
done

while read line; do
    object=${line#tob }
    object=${object%.store*}
    test -e $object && continue # already exists
    
    echo tob-new $object TimeSeries
    test -n "$ok2create" &&
        tob-new $object TimeSeries

done < <(tob $self.parse-good-data)

