#!/bin/sh

log() {
    unset user
    test -n "$USER" && user="user=$USER"
    tob ingest.log.store "$*" $user
    test -n "$USER" && printf "%s\n" "$@"
    exit 0
    }

tob query-server        || log 'query-server failed'
tob parse-dcp-message   || log 'parse-dcp-message failed'
tob parse-good-data     || log 'parse-good-data failed'
tob data.make-view      || log 'data-make-view failed'

log 'success'

