#!/bin/sh

tob=/usr/local/bin/tob

self=.

stage=0
$tob $self.query-server && {
    stage=1
    $tob $self.parse-dcp-message --store && {
        stage=2
        $tob $self.parse-good-data --store && {
            stage=3
            }
        }
    }

logmsg=(
    'query-server failed'
    'parse-dcp-message failed'
    'parse-good-data failed'
    'success'
    )

unset user
test -n "$USER" && user="user=$USER"

$tob ingest/log.store "${logmsg[$stage]}" $user

