#!/bin/sh

error () {
    echo "$@" >&2
    exit 1
    }

test -n "$1" ||
    error "synopsis: init DCPID [NAME ...]"

dcpid=$1 && shift
tob ..validate-dcpid $dcpid ||
    error "dcpid value not validated: $dcpid"
echo $dcpid > @DCPID
chmod -w @DCPID

name="$@"
test -n "$name" ||
    name=$TOB_NEW_target

echo "$name" > @NAME

tob-new ingest          Object     || exit 2
tob-new ingest/log      TimeSeries || exit 2

tob-new dcp-msg         Aggregate  || exit 2
tob-new dcp-msg/good    TimeSeries || exit 2
tob-new dcp-msg/parity  TimeSeries || exit 2
tob-new dcp-msg/missed  TimeSeries || exit 2
tob-new dcp-msg/failed  TimeSeries || exit 2

