#!/bin/sh

# create objects inside the GOES data site object
for ob in query-log query-blob dcp-msg process-dcp-log; do 
    tob-new $ob TimeSeries ||
        exit 2
done

tob-new rawdata Aggregate ||
    exit 2

warn () {
    echo "$*" >&2
    }

dcpid=00000000
name="NO NAME"

# read dcpid and name from tob-new command line...

while test -n "$1"; do

    tag=$1 && shift

    if test $tag == dcpid; then
        dcpid=$1 && shift

    elif test $tag == name; then
        name="$1" && shift

    fi
done

tob ..validate-dcpid $dcpid ||
    warn "dcpid value not validated: $dcpid"


printf "%s=%s\n%s=%s\n" dcpid $dcpid name "$name" > %config

## NOTE: this attribute is for a particular site configuration!
## ... we should move it out of this general-purpose method ...

touch ".data-order-15min=right-to-left"


