#!/usr/bin/perl -w
use strict;
use warnings;

my @messages;
my ($header, $id, $len, $data);
while ( <> ) {
    chomp;
    
    if ( m/^((\S{8})\S{24}00(\d\d\d))(.*)$/ ) { # DCP response header
        push @messages, [ $id, $header, $len, $data ] if defined $id;
        ( $header, $id, $len, $data ) = ( $1, $2, $3, $4 );
        $data .= "\n";
        next;
        }
    $data .= $_ . "\n";
    }
    
foreach my $ref ( @messages ) {
    ($id, $header, $len, $data) = @$ref;
  # printf "%s\n%s %s\n", $header, $id, $len;
    print "$header\n";

    printf "<%s>\n", substr($data, 0, $len);

    printf "[%s]\n", substr($data, $len)
        if length($data) > $len;
    }

