#!/bin/bash

synopsis="${0##*/} [-h] [--test] [--hours HOURS] DCPID SERVER CGI"

error() { printf "%s\n" "$@" >&2; exit 1; }

while test "${1:0:1}" = -; do
    case $1 in
    -h) printf "SYNOPSIS: %s\n" "$synopsis"; exit;;
    --test)
        TESTING=1;;
    --hours)
        hours=$2 && shift;;
    --hours=*)
        hours=${1#*=};;
    *)  error "UNKNOWN OPTION: $1";;
    esac
    shift
done

test $# -ge 3 || error "SYNOPSIS: $synopsis"

dcpid=$1 && shift
test "${#dcpid}" = 8 || error "INVALID DCPID: $dcpid"

server=$1 && shift
cgi_path=$1 && shift

cd ingest || error "NO ingest/ DIRECTORY FOUND IN $PWD"

test -n "$hours" || hours=$(( ( $(date +%s)-$(stat -c %Y @header))/3600)) ||
    error "FAILED to get hours since @header was last written"

# prior to May2010:
# "http://lrgseddn1.cr.usgs.gov/cgi-bin/fieldtest.pl?DCPID=$dcpid&SINCE=$hours"
# 
# as of 03may2010:
# "http://lrgseddn3.cr.usgs.gov/cgi-bin/fieldtest.pl?DCPID=326AF6FE&SINCE=8"
#
# EDDN home page: http://eddn.usgs.gov/
# DCP Field Test - Low-Bandwidth Message Access:
#       http://eddn.usgs.gov/fieldtest.html

test -n "$TESTING" && {
    w3m -dump -cols 10000 \
        "http://$server/${cgi_path}?DCPID=$dcpid&SINCE=$hours" 
    exit
    }

w3m -dump -cols 10000 \
    "http://$server/${cgi_path}?DCPID=$dcpid&SINCE=$hours" |
    tee @raw |
    awk "/^$dcpid/{print substr(\$1,1,37)}" > .@_header

cmp .@_header @header > /dev/null 2>&1 && error "DUPLICATE DCP HEADER"

mv .@_header @header

# w3m -dump -cols 10000 \
#     "http://$server/${cgi_path}?DCPID=$dcpid&SINCE=$hours" > @raw

# build a descriptor line for heading accumulated raw query results

now=$(date --iso=seconds)

ym=${now%-??T*}

lines=$(wc -l<@raw)

unset user &&
    test -n "$USER" &&
        user="user=$USER"

fields=( $now $server $dcpid qryhrs=$hours lines=$lines $user )

allraw="@$ym-allraw"

echo "# ${fields[@]}" >> "$allraw"

cat @raw >> "$allraw"

test "@allraw" == "$(readlink $allraw)" ||
    ln -sf $allraw @allraw


