#!/bin/sh

hrs="$1"
test -n "$hrs" ||
    hrs=1

test -e %config ||
    exit 2

unset dcpid name
while IFS='=' read tag value; do
  # echo $tag $value
    test -n "$tag" || continue
    test ${tag:0:1} == '#' && continue
    if test $tag == dcpid; then
        dcpid=$value
    elif test $tag == name; then
        name=$value
    fi
done < %config

tob ..validate-dcpid $dcpid ||
    exit 2

w3m -dump -cols 10000 "http://lrgseddn1.cr.usgs.gov/cgi-bin/fieldtest.pl?DCPID=$dcpid&SINCE=$hrs" \
    > @results

lines=$(wc -l @results)
lines=${lines% *}

loginfo="id=$dcpid,lines=$lines"

test -n "$USER" &&
    loginfo="$loginfo,user=$USER"

tob query-log.store $loginfo

tob query-blob.store < @results

now=$(date --iso=seconds)

# store a last-ditch flat file of log messages and results:
echo \#query: $now,$loginfo >> @alldata
cat @results >> @alldata

