#!/bin/bash

synopsis="${0##*/} [-h] DCPID SERVER CGI-PATH [HOURS]"

error() { printf "%s\n" "$@" >&2; exit 1; }

while test "${1:0:1}" = -; do
    case $1 in
    -h) printf "synopsis: %s\n" "$synopsis"; exit;;
    *)  error "unknown option: $1";;
    esac
    shift
done

dcpid=$1 && shift || error "synopsis: $synopsis"
server=$1 && shift
cgi_path=$1 && shift
hours=168
test -n "$1" && hours=$1 && shift

# simple/crude validation of dcpid value:
test "${#dcpid}" = 8 || error "invalid DCPID: $dcpid"

cd ingest || exit 1

# prior to May2010:
# "http://lrgseddn1.cr.usgs.gov/cgi-bin/fieldtest.pl?DCPID=$dcpid&SINCE=$hours"
# 
# as of 03may2010:
# "http://lrgseddn3.cr.usgs.gov/cgi-bin/fieldtest.pl?DCPID=326AF6FE&SINCE=8"
#
# EDDN home page: http://eddn.usgs.gov/
# DCP Field Test - Low-Bandwidth Message Access:
#       http://eddn.usgs.gov/fieldtest.html

w3m -dump -cols 10000 \
    "http://$server/${cgi_path}?DCPID=$dcpid&SINCE=$hours" |
    tee @raw |
    awk "/^$dcpid/{print substr(\$1,1,37)}" > .@_header

cmp .@_header @header > /dev/null 2>&1 && {
    echo duplicate DCP header >&2
    exit 1
    }

mv .@_header @header

# w3m -dump -cols 10000 \
#     "http://$server/${cgi_path}?DCPID=$dcpid&SINCE=$hours" > @raw

# build a descriptor line for heading accumulated raw query results

now=$(date --iso=seconds)

ym=${now%-??T*}

lines=$(wc -l<@raw)

unset user &&
    test -n "$USER" &&
        user="user=$USER"

fields=( $now $server $dcpid qryhrs=$hours lines=$lines $user )

allraw="@$ym-allraw"

echo "# ${fields[@]}" >> "$allraw"

cat @raw >> "$allraw"

test "@allraw" == "$(readlink $allraw)" ||
    ln -sf $allraw @allraw


