#!/bin/bash

echo $(<@DCPID) $(<@NAME)
tob ingest.log.get last 1

showif="AirTemp ta ATemp VB Battery Batv"

cd data-raw 2>/dev/null || {
    printf "\n"
    exit
    }

for ob in *; do
    test "${showif#*$ob}" == "$showif" &&
        continue
    printf "%s\t%s\n"  "$(tob $ob.get last 1)" $ob
done

