#!/bin/sh

error () {
    echo "$*" >&2
    exit 1
    }

test -n "$1" ||
    error "synopsis: $TOB_object.$TOB_method DCPID"

dcpid=$1 && shift
    
test ${#dcpid} == 8 ||
    error "dcpid value has ${#dcpid} characters, should be 8: $dcpid"

i=0
while test $i -lt 8; do
  # echo $i
    c=${dcpid:$i:1}
    test "${c/[0-9a-fA-F]}" == "" ||
        error "invalid character $c at position $(($i+1)): $dcpid"
    i=$(($i+1))
done

