#!/bin/sh

cat << END_HELP_SCREEN
NAME
    DataSite/GOES/WaterLog -- GOES data platform using a WaterLog datalogger

ATTRIBUTES
    .data-order-15min=right-to-left --
        interpret 15-minute data in hourly messages as written from right
        to left, i.e., so that the newest data is on the left
    
CHAINING TO PARENT CLASS...
END_HELP_SCREEN

# the super.help method isn't resolving, so add a horrible kludge...
tob ..super.help 2>/dev/null ||
    .^/^/help 2>/dev/null ||
        ^/^/help 2>/dev/null ||
            echo no help method found for parent class 


